version: '3.8'
services:
  db:
    image: alpine:3.19.1
    command: ["sh", "-c", "touch /db/book_app_dev.db && tail -f /dev/null"]
    volumes:
      - db_data:/db

  app:
    build: .
    environment:
      - DATABASE_PATH=/db/book_app_dev.db
      - PHX_SERVER=true
      - SECRET_KEY_BASE=pdNRKWTzPe8IGmeqcFhP6IibMjnfRBGDlukkYAcnD1AuVC7et59EWMXKMvrWUONa
      - SERVE_STATIC_ASSETS=false
      - IMAGE_STORAGE_PATH=priv/static/uploads
      - REDIS_URL=redis://redis:6379
      - OPENSEARCH_URL=http://opensearch:9200
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
      - opensearch
    volumes:
      - db_data:/db
      - uploads_data:/app/priv/static/uploads

  caddy:
    image: caddy:2
    ports:
      - "2015:2015"
    volumes:
      - ./caddy.json:/etc/caddy/caddy.json
      - uploads_data:/root/projects/book_app/priv/static/uploads
    depends_on:
      - app
    command: caddy run --config /etc/caddy/caddy.json

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  opensearch:
    image: opensearchproject/opensearch:2.11.1
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:
  uploads_data: