import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :book_app, BookAppWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configure Redis cache for production
config :book_app,
  cache_adapter: :redis,
  redis_url: System.get_env("REDIS_URL", "redis://redis:6379")

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Configure your database
config :book_app, BookApp.Repo,
  database: System.get_env("DATABASE_PATH") || "priv/repo/book_app_prod.db",
  pool_size: 5

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
